export const LANDING = "/"
export const LOGIN = "/login"
export const LOGOUT = "/logout"
export const DASHBOARD = "/dashboard"
export const ISSUES = "/issues"
export const ELABORATE = "/elaborate"
export const SHAREFILES = "/shareFiles"